import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "@/styles/main.css";
import "./globals.css";
import MainLayout from "@/components/MainLayout";
import ScrollToTop from "@/components/ScrollToTop";
import { VideoTimeProvider } from "@/contexts/VideoTimeContext";
import { DemoModalProvider } from "@/contexts/DemoModalContext";
import { MobileHomeVideoProvider } from "@/components/mobile/MobileHomeVideoContext";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Vayyar Care AI",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${geistMono.variable} antialiased overflow-x-hidden bg-white`}
            >
                <VideoTimeProvider>
                    <DemoModalProvider>
                        <MobileHomeVideoProvider>
                            <ScrollToTop />
                            <MainLayout>{children}</MainLayout>
                        </MobileHomeVideoProvider>
                    </DemoModalProvider>
                </VideoTimeProvider>
            </body>
        </html>
    );
}
