import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "@/styles/main.css";
import "./globals.css";
import AppShell from "@/components/AppShell";
import { VideoTimeProvider } from "@/contexts/VideoTimeContext";
import { MobileHomeVideoProvider } from "@/components/mobile/MobileHomeVideoContext";
import { RewindProvider } from "@/contexts/RewindContext";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Vayyar Care AI",
    description: "Generated by create next app",
    icons: [
        {
            rel: "icon",
            url: "images/vayyar-logo.png",
        },
    ],
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${geistMono.variable} antialiased overflow-x-hidden bg-white`}
            >
                <VideoTimeProvider>
                    <MobileHomeVideoProvider>
                        <RewindProvider>
                            <AppShell>{children}</AppShell>
                        </RewindProvider>
                    </MobileHomeVideoProvider>
                </VideoTimeProvider>
            </body>
        </html>
    );
}
